name: PHP CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-run-container:
    runs-on: self-hosted  # run on your own machine

    env:
      APP_PORT: 8080

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clean existing container (if any)
        run: |
          docker stop php-container || true
          docker rm php-container || true

      - name: Build Docker Image
        run: docker build -t rahulhub1313/mini-cicd-php .

      - name: Run Docker Container
        run: docker run -d --name php-container -p ${{ env.APP_PORT }}:80 rahulhub1313/mini-cicd-php

      - name: Check Container Status
        run: docker ps

      - name: Validate from localhost
        run: |
          sleep 3
          curl -s http://localhost:${{ env.APP_PORT }} | grep "Hello from PHP"
